.github/workflows/push_container.yaml

If a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.
For example, even though this tag was created https://github.com/stakater/mto-docs/releases/tag/v0.0.2, it never triggered a release flow.
Add the ability to specify another custom token so flows are triggered as expected.

GitHub token for release template

---

.github/workflows/pull_request_container_build.yaml
.github/workflows/push_container_only.yaml

Enable setting build-context when building Dockerfile images, this removes the need to be limited to a certain ref base context and instead provide additional build contexts via parameters during build time.

Docker build context

---

.github/workflows/pull_request_container_build.yaml
.github/workflows/push_container_only.yaml

https://docs.docker.com/engine/reference/commandline/buildx_build/#secret
When using build contexts that use private GitHub repositories, it is necessary to specify `GIT_AUTH_TOKEN` secret for buildkit to read from the repo: https://github.com/moby/buildkit/blob/811b22e35c31cbe567f571562eba013b351a77c5/client/llb/source.go#L245

Add the ability to provide Docker secrets

---

.github/workflows/pull_request_doc_qa.yaml

Docs are usually at least 3 directory levels deep

Update max-depth for link checking

---

.github/workflows/pull_request_closed.yaml
.github/workflows/pull_request_versioned_doc.yaml

For versioned doc, when doing pull requests for Renovate PRs, it creates a temporary version with forward slash however mike doesn't allow forward slashes in versions. For example here https://github.com/stakater/mto-docs/actions/runs/4819621365/jobs/8583063348?pr=20 we get:
```sh
Run mike deploy --push -b pull-request-deployments $HEAD_REF
error: 'renovate/stakater-.github-0.x' is not a valid version
```
Do a bash string substitution, where we replace all matches of forward slash with dash:
```sh
> TEMP=renovate/with/many/slashes
> echo ${TEMP//\//-}
renovate-with-many-slashes
```

String substitution

---

.github/workflows/pull_request_container_build.yaml

we have a submodule in a repo which does not checkout in workflow. need to enable submodule checkout.

enabling submodule checkout, needed for mto-docs

---

.github/workflows/mkdocs_branch_deleted.yaml
.github/workflows/mkdocs_pull_request_closed.yaml
.github/workflows/mkdocs_pull_request_versioned_doc.yaml
.github/workflows/mkdocs_push_versioned_doc.yaml
.github/workflows/pull_request_container_build.yaml
.github/workflows/push_container_only.yaml
.github/workflows/release.yaml
.github/workflows/release_template.yaml

Why new workflows? Because we have created a common mkdocs theme project which will be used in combination with existing mkdocs projects. We need to enable submodules download as well as some changes in existing workflows to run scripts.
We have not modified the existing workflows for docs because we do not want other docs projects to get affected while we roll out new way of mkdocs one by one. Once we have done the transition for all projects, we will remove the old workflows.

Enable submodule checkout and adding new workflows for mkdocs related repos

---

.github/workflows/pull_request_doc_qa.yaml

The Vale GitHub action has until now not been pinned to a particular version, so the latest version has always inadvertently been used. Vale had a major version update 10 h ago that broke all current pipelines. Pin the version to the last minor version, so we can do a controlled upgrade to the latest version.

Pin vale version

---

.github/workflows/pull_request_doc_qa.yaml
renovate.json

Updates:
* Migrate to Vale 3
* Also switch to using Vale natively, because `reviewdog` does not treat errors as expected: https://github.com/errata-ai/vale-action/issues/116
* Add Renovate custom manager to update GitHub release attachments

Vale 3 migration

---

.github/workflows/pull_request_doc_qa.yaml

Renovate did not update the filename in https://github.com/stakater/.github/pull/92, the regex manager need to be updated if it is even possible to match it properly

Fix Vale update

---

.github/workflows/push_container.yaml

Submodules are currently not checked out during container push, causing builds that depend on submodules to fail

Submodule checkout

---

.github/workflows/publish_operator_image_and_bundle.yaml

Revert "Run go mod tidy in publish_operator_image_and_bundle.yaml workflow"

---

.github/workflows/publish_operator_image_and_bundle.yaml
.github/workflows/push.yaml
.github/workflows/release.yaml

From what I can see, a dedicated token is not needed, and the generic github token can be used instead

Change to generic github token

---

.github/workflows/push.yaml

Need to change token: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
```
if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.
```
Correct the job name.
Use later version of action, this should be safe to use, latest version doesn't work.

Need to change token to trigger release

---

.github/workflows/pull_request_container_build.yaml

Many PR images have been incorrectly published in a subfolder since `CONTAINER_REGISTRY_URL` already contains the subpath in the registry, for example PR images for mto-docs are currently published in `https://ghcr.io/stakater/stakater/mto-docs` when they should be in `https://ghcr.io/stakater/mto-docs`
Subsequent PRs need to update all uses of this template, so they use the correct value for `CONTAINER_REGISTRY_URL`

Image repository path

---

.github/workflows/branch_deleted.yaml
.github/workflows/push_versioned_doc.yaml
.github/workflows/rdlm_acquire.yaml
.github/workflows/rdlm_release.yaml

When viewing versioned documentation, and selecting a version that is not the latest, the banner warning about not being on the latest version should only display when the user has not selected the latest released version. Currently, it treats `main` as the latest version, but `main` should not be the `latest` alias - instead, the versioned doc pipeline should always require to specify which version is the latest, and the `latest` alias should be updated to be based on the latest doc version provided.
For example, `versions.json` could look like this:
```json
[
{
"version": "main",
"title": "main",
"aliases": [
"latest"
]
},
{
"version": "1.0",
"title": "1.0",
"aliases": []
}
]
```
When the versioned doc pipeline builds the docs for any version, and it specifies `1.0` as the latest …

Enable setting latest doc version for multiple versioned doc

---

.github/workflows/pull_request_versioned_doc.yaml

* When deploying PR builds, update latest alias and set default. Otherwise, the root url will just return 404, and the user has to manually add the PR branch in the path to view the PR docs
* Add a comment in the PR pointing to where the docs are deployed for easy review

When deploying PR builds, update latest alias

---

.github/workflows/pull_request_closed.yaml
.github/workflows/pull_request_versioned_doc.yaml

When deploying a PR branch, it currently fails with:
```txt
error: '${HEAD_REF//\\//-}' is not a valid version
Error: Process completed with exit code 1.
```
The fix in this PR was tested successfully in https://github.com/stakater/mto-docs/pull/208/commits/f9f8ba58b7107177fb12b803a7237b3218f95c52

Fix head ref variable

---

.github/workflows/pull_request_doc_qa.yaml

`nosborn/github-action-markdown-cli` is not very active and seems to ignore errors sometimes, switch to a more actively maintained action for running the linter. Both actions rely on the same [markdownlint](https://github.com/DavidAnson/markdownlint).
Tested successfully in https://github.com/stakater/saap-docs/pull/342/commits/4bcb1d5e4307e210e74b748f7ec5d00fab1245ee
The only update that is needed when using this template is that you need to be more specific when specifying the doc source, for example from:
```yaml
DOC_SRC: content README.md
```
to:
```yaml
DOC_SRC: content/**/*.md README.md
```

Update markdown linter

---

.github/workflows/pull_request_container_build.yaml

The step for setting the image output is using `IMAGE_REPOSITORY` but that env var is created in a step that is after that step, it needs to go before it is actually used. Currently, it is empty so the image output is like `:SNAPSHOT-PR-556-1377a4ca`.

Fix image path

---

.github/workflows/pull_request_container_build.yaml

The `IMAGE_PATH` output is all empty right now, and that is because it contains `CONTAINER_REGISTRY_URL` which is a secret, and secrets cannot be passed around between jobs. There are ways to pass around secrets by encoding and decoding them, using actions such as https://github.com/cloudposse/github-action-secret-outputs, but the registry URL doesn't need to be a secret anyway and can be passed around in clear text as an input. We always specify the secret as clear text anyway in our current workflows.

Fix bug with empty image path

---

.github/workflows/pull_request_versioned_doc.yaml

When creating PRs for versioned doc, we want to run tests as part of the pipeline, and then we need the branch name that will be used to set the version in the temporarily built docs as output from the pipeline

Get branch as output for versioned doc

---

.github/workflows/pull_request_doc_qa.yaml

Seems to work as expected, tested in https://github.com/stakater/support-docs/pull/38:
* It was failing temporarily for one link and ran twice: https://github.com/stakater/support-docs/actions/runs/13042066535/job/36385918703
* Added a delay of 60 s to take into account that temporarily broken links might take some time to recover
* In a later run it was successful on first run and only ran once: https://github.com/stakater/support-docs/actions/runs/13042123457/job/36386087068

Rerun linkcheck if it fails
